# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 08:26
from __future__ import unicode_literals

import app_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0015_auto_20161208_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser_size',
            field=models.CharField(null=True, blank=True, verbose_name='teaser size'),
        ),
    ]
