# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 08:26
from __future__ import unicode_literals

import app_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0016_auto_20170207_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='twitter',
            field=models.CharField(default='', verbose_name='twitter name', max_length=255, blank=True),
        ),
    ]
